### ISSUE TITLE
Out of range error when unzipping archive

### ISSUE THREAD

**Issue by mcarson-sandia** [Majored/rs-async-io-utilities#1]
After using rs-async-zip to zip the [curl git repo](https://github.com/curl/curl) I was unable to unzip it using rs-async-zip and got the following error:

```
writting file to "/home/mcarson/projects/zip-test/curl/.git/objects/pack/pack-38d8b4a0b22b1f59aac4f4ff9ec3155e65885203.pack"
thread 'main' panicked at 'range start index 16387 out of range for slice of length 16384', /home/mcarson/projects/public-deps/rs-async-io-utilities/src/readers/delimiter_reader.rs:91:38
```

However unzip is able to unpack the archive and rs-async-zip can unzip the archive when I zip the same files with zip. I am also able to unzip the file using [zip-rs](https://github.com/zip-rs/zip) so it appears to be an issue with unzipping rather then zipping.

**Comment by Majored** [comment]
Should be resolved with https://github.com/Majored/rs-async-io-utilities/pull/3 thanks to @darrell-roberts.

I'll go ahead and close this but let me know if you run into this again.
